FROM node:14.5.0-alpine3.12
#en esta carpeta voy a instalar mis dependenicias
#la carpeta /home/node/app va ser propiedad del usuario node
RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
